module.exports = {
	data:{
		'1012301':{
			login: "octocat",
			id: 1012301,
			node_id: "MDQ6VXNlcjE=",
			avatar_url: "https://github.com/images/error/octocat_happy.gif",
			gravatar_id: "",
			url: "https://api.github.com/users/octocat",
			html_url: "https://github.com/octocat",
			followers_url: "https://api.github.com/users/octocat/followers",
			following_url: "https://api.github.com/users/octocat/following{/other_user}",
			gists_url: "https://api.github.com/users/octocat/gists{/gist_id}",
			starred_url: "https://api.github.com/users/octocat/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/octocat/subscriptions",
			organizations_url: "https://api.github.com/users/octocat/orgs",
			repos_url: "https://api.github.com/users/octocat/repos",
			events_url: "https://api.github.com/users/octocat/events{/privacy}",
			received_events_url: "https://api.github.com/users/octocat/received_events",
			type: "User",
			site_admin: false,
			name: "monalisa octocat",
			company: "GitHub",
			blog: "https://github.com/blog",
			location: "San Francisco",
			email: "octocat@github.com",
			hireable: false,
			bio: "There once was...",
			twitter_username: "monatheoctocat",
			public_repos: 2,
			public_gists: 1,
			followers: 20,
			following: 0,
			created_at: "2008-01-14T04:33:35Z",
			updated_at: "2008-01-14T04:33:35Z",
			private_gists: 81,
			total_private_repos: 100,
			owned_private_repos: 100,
			disk_usage: 10000,
			collaborators: 8,
			two_factor_authentication: true,
			plan: {
				name: "Medium",
				space: 400,
				private_repos: 20,
				collaborators: 0
			}
		},
		'1725104':{
			login: "denver",
			id: 1725104,
			node_id: "MDQ6VXNlcjE3MjUxMDQ=",
			avatar_url: "https://avatars.githubusercontent.com/u/1725104?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/denver",
			html_url: "https://github.com/denver",
			followers_url: "https://api.github.com/users/denver/followers",
			following_url: "https://api.github.com/users/denver/following{/other_user}",
			gists_url: "https://api.github.com/users/denver/gists{/gist_id}",
			starred_url: "https://api.github.com/users/denver/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/denver/subscriptions",
			organizations_url: "https://api.github.com/users/denver/orgs",
			repos_url: "https://api.github.com/users/denver/repos",
			events_url: "https://api.github.com/users/denver/events{/privacy}",
			received_events_url: "https://api.github.com/users/denver/received_events",
			type: "User",
			site_admin: false,
			name: "Denver Peterson",
			company: "Github",
			blog: "",
			location: "San Francisco, CA",
			email: null,
			hireable: null,
			bio: null,
			twitter_username: null,
			public_repos: 105,
			public_gists: 0,
			followers: 37,
			following: 113,
			created_at: "2012-05-10T03:18:01Z",
			updated_at: "2022-08-15T15:56:53Z",
			// Dummy Data
			private_gists: 149,
			total_private_repos: 77,
			owned_private_repos: 32,
			disk_usage: 31011,
			collaborators: 19,
			two_factor_authentication: true,
			plan: {
				name: "Pro",
				space: 999,
				private_repos: 47,
				collaborators: 19
			}
		},
		'5502060':{
			login: "jasontylerb",
			id: 5502060,
			node_id: "MDQ6VXNlcjU1MDIwNjA=",
			avatar_url: "https://avatars.githubusercontent.com/u/5502060?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/jasontylerb",
			html_url: "https://github.com/jasontylerb",
			followers_url: "https://api.github.com/users/jasontylerb/followers",
			following_url: "https://api.github.com/users/jasontylerb/following{/other_user}",
			gists_url: "https://api.github.com/users/jasontylerb/gists{/gist_id}",
			starred_url: "https://api.github.com/users/jasontylerb/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/jasontylerb/subscriptions",
			organizations_url: "https://api.github.com/users/jasontylerb/orgs",
			repos_url: "https://api.github.com/users/jasontylerb/repos",
			events_url: "https://api.github.com/users/jasontylerb/events{/privacy}",
			received_events_url: "https://api.github.com/users/jasontylerb/received_events",
			type: "User",
			site_admin: false,
			name: "Jason Burns",
			company: null,
			blog: "",
			location: "San Diego, CA",
			email: null,
			hireable: null,
			bio: null,
			twitter_username: null,
			public_repos: 3,
			public_gists: 0,
			followers: 2,
			following: 2,
			created_at: "2013-09-20T13:47:39Z",
			updated_at: "2020-09-13T03:44:48Z",
			private_gists: 0,
			total_private_repos: 1,
			owned_private_repos: 1,
			disk_usage: 9074,
			collaborators: 0,
			two_factor_authentication: false,
			plan: {
					name: "Free",
					space: 976562499,
					collaborators: 0,
					private_repos: 10000
			}
		},
		'1000001':{
			login: "tommydohmke",
			id: 1000001,
			node_id: "ABZ1GCLlbcU0TXRqMaZ=",
			avatar_url: "https://avatars.githubusercontent.com/u/5502060?v=4",
			gravatar_id: "",
			url: "https://api.github.com/users/tommydohmke",
			html_url: "https://github.com/tommydohmke",
			followers_url: "https://api.github.com/users/tommydohmke/followers",
			following_url: "https://api.github.com/users/tommydohmke/following{/other_user}",
			gists_url: "https://api.github.com/users/tommydohmke/gists{/gist_id}",
			starred_url: "https://api.github.com/users/tommydohmke/starred{/owner}{/repo}",
			subscriptions_url: "https://api.github.com/users/tommydohmke/subscriptions",
			organizations_url: "https://api.github.com/users/tommydohmke/orgs",
			repos_url: "https://api.github.com/users/tommydohmke/repos",
			events_url: "https://api.github.com/users/tommydohmke/events{/privacy}",
			received_events_url: "https://api.github.com/users/tommydohmke/received_events",
			type: "Employee",
			site_admin: true,
			name: "Gerald T. Hubbard",
			company: "Github",
			blog: "",
			location: "San Francisco, CA",
			email: null,
			hireable: null,
			bio: null,
			twitter_username: null,
			public_repos: 4,
			public_gists: 0,
			followers: 1701,
			following: 111,
			created_at: "2012-01-23T07:27:11Z",
			updated_at: "2019-11-03T18:22:34Z",
			private_gists: 0,
			total_private_repos: 1,
			owned_private_repos: 1,
			disk_usage: 23077,
			collaborators: 0,
			two_factor_authentication: false,
			plan: {
					name: "Employee",
					space: 132178901,
					collaborators: 999,
					private_repos: 0
			}
		}
	}
}